server:
  port: 10012

#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp

# spring.ai.ollama.base-url=http://10.31.128.110:9999
# spring.ai.ollama.chat.options.model=Qwen2-7b:latest
#  spring.mvc.async.request-timeout=60000 # 单位毫秒（60秒）
spring:
#  ai:
#    ollama:
#      base-url: http://localhost:11434/
#      chat:
#        options:
#          model: deepseek-r1:1.5b
  mvc:
    async:
      request-timeout: 3600000 # 设置请求超时时间，单位毫秒（600秒）
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    load-on-startup: 1
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 30s
      database: 2
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  application:
    name: kantboot
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kantboot_new_new?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        physical_naming_strategy: com.kantboot.util.jpa.strategy.NoForeignKeyNamingStrategy
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false

kantboot:
  isAutoTranslate: true
